recipe:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  license: Apache-2.0
  name: "mate-desktop"
  description: "MATE desktop with x2go"
  inputs: null
  base:
    - "debian"
    - "centos"
  parent: null
  tags:
    - "desktop"
    - "software"