recipe:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  license: Apache-2.0
  name: "slurm_master"
  description: "Slurm cluster master [BETA]"
  inputs: null
  base:
    - "debian"
  parent: null
  tags:
    - "master"
    - "slurm"
