recipe:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  license: Apache-2.0
  name: "slurm_slave"
  description: "Slurm cluster slave [BETA]"
  inputs: null
  base:
    - "debian"
  parent: null
  tags:
    - "slave"
    - "slurm"
