recipe:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  license: Apache-2.0
  name: "docker"
  description: "install docker"
  inputs: null
  base:
    - "debian"
    - "centos"
  parent: null
  tags:
    - "docker"
    - "software"