application:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  name: "simple-vm"
  description: "Just a basic virtual machine"
  template: "simple/v1.0"
  recipes:
    recipes_vm:
      - "disk_block_automount/v1.0"
      - "share_automount/v1.0"
  tags:
    - "simple"
