recipe:
  author: Olivier Sallou <olivier.sallou@irisa.fr>
  license: Apache-2.0
  name: "common-packages"
  description: "install useful packages"
  inputs: null
  base:
    - "debian"
    - "centos"
  parent: null
  tags:
    - "software"